version: 2.1

executors:
  yocto-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: yocto-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping libsdl1.2-dev xterm
      - run:
          name: Setup Yocto Project
          command: |
            git clone git://git.yoctoproject.org/poky.git
            cd poky
            git checkout -b zeus origin/zeus
            source oe-init-build-env
      - run:
          name: Configure Yocto Build
          command: |
            cd poky
            source oe-init-build-env
            bitbake core-image-minimal
      - run:
          name: Run QEMU
          command: |
            cd poky
            source oe-init-build-env
            runqemu qemux86-64
      - run:
          name: Run Tests
          command: |
            cd poky
            source oe-init-build-env
            # Example test script, replace with your actual test commands
            ./run-tests.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

