version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:20.04

    steps:
      - checkout

      # Install necessary dependencies
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y qemu-system-x86 qemu-kvm curl

      # Download and prepare Ubuntu Core image
      - run:
          name: Download Ubuntu Core
          command: |
            curl -O http://cdimage.ubuntu.com/ubuntu-core/20/stable/current/ubuntu-core-20-amd64.img.xz
            unxz ubuntu-core-20-amd64.img.xz

      # Run QEMU with Ubuntu Core image
      - run:
          name: Run QEMU
          command: |
            qemu-system-x86_64 -nographic -smp 2 -m 1024 -hda ubuntu-core-20-amd64.img &
            sleep 30 # wait for QEMU to start

      # Run your tests
      - run:
          name: Run tests
          command: |
            # Add commands to run your tests here, for example:
            echo "Running tests..."

      # Collect test results and update dashboard
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

